### ISSUE TITLE
Fix "?" references in PDF files

### ISSUE THREAD

**Issue by xamidi** [metamath/metamath-website-scripts#19]
Some PDF files such as https://us.metamath.org/downloads/finiteaxiom.pdf need to be compiled twice, in order for references to work.

**Fix:**
Duplicate the `pdflatex` call ([this line](https://github.com/metamath/metamath-website-scripts/blob/8d81a0c1ab3e433b335b4e6a3bdc364d277b4946/build-website.sh#L143)) in [build-website.sh](https://github.com/metamath/metamath-website-scripts/blob/main/build-website.sh).

**Comment by digama0** [comment]
could you submit this as a PR?

**Comment by xamidi** [comment]
> could you submit this as a PR?

Sure, single line PR is ready. 😅

**Comment by xamidi** [comment]
It still seems broken. Were the scripts ever used to rebuild the PDFs after this patch?

**November 2025**: The changes [were finally applied](https://groups.google.com/g/metamath/c/m5tqOMJykeQ/m/1x-mwCH7CAAJ) …
